#!/bin/bash -l
#SBATCH --image=td115/jetscape-normal:latest
#SBATCH --nodes=1 

#SBATCH --time=00:05:00 
#SBATCH --qos=regular

#SBATCH --mail-type ALL
#SBATCH --mail-user <email>

#SBATCH --license=SCRATCH   #note: specify license need for the file systems your job needs, such as SCRATCH,project

#SBATCH --constraint=haswell

#SBATCH --volume="/global/cscratch1/sd/<user>:/home"

#SBATCH --error "/global/cscratch1/sd/<user>/slurm/%x-%j.err"

#SBATCH --output "/global/cscratch1/sd/<user>/slurm/%x-%j.out"

srun -n 1 shifter --image=docker:<user>/<name>:<version> <path to executable>

